services:

  ckan-mcp-server-stdio:
    profiles:
      - stdio
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    entrypoint: ["uv", "run", "ckan-mcp-server", "--transport", "stdio"]

  ckan-mcp-server:
    profiles:
      - sse
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    entrypoint: ["uv", "run", "ckan-mcp-server","--transport", "sse","--port","8000","--host","0.0.0.0"]
